let users = [
  {
    id: 1,
    first_name: "Erda",
    last_name: "Waddingham",
    email: "&quot;ewaddingham0@mysql.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Bev",
    last_name: "Gavin",
    email: "&quot;bgavin1@archive.org",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Tabb",
    last_name: "Murphy",
    email: "&quot;tmurphy2@ameblo.jp",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Elberta",
    last_name: "Hansom",
    email: "&quot;ehansom3@infoseek.co.jp",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Chantalle",
    last_name: "Espinoza",
    email: "&quot;cespinoza4@t.co",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Chickie",
    last_name: "Bail",
    email: "&quot;cbail5@domainmarket.com",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Conney",
    last_name: "Soot",
    email: "&quot;csoot6@noaa.gov",
    gender: "Male",
  },
  {
    id: 8,
    first_name: "Emlynne",
    last_name: "Tabourier",
    email: "&quot;etabourier7@51.la",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Shadow",
    last_name: "Neicho",
    email: "&quot;sneicho8@nifty.com",
    gender: "Male",
  },
  {
    id: 10,
    first_name: "Caro",
    last_name: "Dunnan",
    email: "&quot;cdunnan9@biglobe.ne.jp",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Sissy",
    last_name: "Summergill",
    email: "&quot;ssummergilla@google.nl",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Gerda",
    last_name: "Hallex",
    email: "&quot;ghallexb@bloglovin.com",
    gender: "Female",
  },
  {
    id: 13,
    first_name: "Maurizia",
    last_name: "Vale",
    email: "&quot;mvalec@tuttocitta.it",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Benjie",
    last_name: "Gilbee",
    email: "&quot;bgilbeed@wp.com",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Prescott",
    last_name: "Ariss",
    email: "&quot;parisse@networksolutions.com",
    gender: "Male",
  },
  {
    id: 16,
    first_name: "Hazel",
    last_name: "Osbourn",
    email: "&quot;hosbournf@earthlink.net",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Courtnay",
    last_name: "McIlriach",
    email: "&quot;cmcilriachg@usa.gov",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Betta",
    last_name: "Bilby",
    email: "&quot;bbilbyh@miibeian.gov.cn",
    gender: "Female",
  },
  {
    id: 19,
    first_name: "Dalia",
    last_name: "Hanhardt",
    email: "&quot;dhanhardti@mozilla.org",
    gender: "Female",
  },
  {
    id: 20,
    first_name: "Andrey",
    last_name: "Costin",
    email: "&quot;acostinj@nydailynews.com",
    gender: "Male",
  },
  {
    id: 21,
    first_name: "Gilly",
    last_name: "Proven",
    email: "&quot;gprovenk@google.ca",
    gender: "Female",
  },
  {
    id: 22,
    first_name: "Tull",
    last_name: "Petch",
    email: "&quot;tpetchl@phpbb.com",
    gender: "Male",
  },
  {
    id: 23,
    first_name: "Ailsun",
    last_name: "Saltrese",
    email: "&quot;asaltresem@house.gov",
    gender: "Female",
  },
  {
    id: 24,
    first_name: "Kim",
    last_name: "Roseveare",
    email: "&quot;krosevearen@deliciousdays.com",
    gender: "Female",
  },
  {
    id: 25,
    first_name: "Kimmie",
    last_name: "Gallandre",
    email: "&quot;kgallandreo@hp.com",
    gender: "Genderfluid",
  },
  {
    id: 26,
    first_name: "Serena",
    last_name: "Blainey",
    email: "&quot;sblaineyp@constantcontact.com",
    gender: "Female",
  },
  {
    id: 27,
    first_name: "Harman",
    last_name: "Louys",
    email: "&quot;hlouysq@pagesperso-orange.fr",
    gender: "Male",
  },
  {
    id: 28,
    first_name: "Pepe",
    last_name: "McGaughey",
    email: "&quot;pmcgaugheyr@google.de",
    gender: "Genderfluid",
  },
  {
    id: 29,
    first_name: "Zeke",
    last_name: "Drews",
    email: "&quot;zdrewss@yellowpages.com",
    gender: "Male",
  },
  {
    id: 30,
    first_name: "Shirleen",
    last_name: "Dybbe",
    email: "&quot;sdybbet@jalbum.net",
    gender: "Female",
  },
  {
    id: 31,
    first_name: "Calvin",
    last_name: "Covill",
    email: "&quot;ccovillu@apache.org",
    gender: "Male",
  },
  {
    id: 32,
    first_name: "Arnoldo",
    last_name: "Stittle",
    email: "&quot;astittlev@domainmarket.com",
    gender: "Male",
  },
  {
    id: 33,
    first_name: "Horatius",
    last_name: "Stancliffe",
    email: "&quot;hstancliffew@nps.gov",
    gender: "Male",
  },
  {
    id: 34,
    first_name: "Zelma",
    last_name: "McRannell",
    email: "&quot;zmcrannellx@cnbc.com",
    gender: "Female",
  },
  {
    id: 35,
    first_name: "Sophey",
    last_name: "MacKee",
    email: "&quot;smackeey@boston.com",
    gender: "Female",
  },
  {
    id: 36,
    first_name: "Gwennie",
    last_name: "Ascroft",
    email: "&quot;gascroftz@ted.com",
    gender: "Female",
  },
  {
    id: 37,
    first_name: "Tresa",
    last_name: "Leney",
    email: "&quot;tleney10@vinaora.com",
    gender: "Female",
  },
  {
    id: 38,
    first_name: "Trey",
    last_name: "Tivolier",
    email: "&quot;ttivolier11@usda.gov",
    gender: "Male",
  },
  {
    id: 39,
    first_name: "Keefer",
    last_name: "Kroin",
    email: "&quot;kkroin12@japanpost.jp",
    gender: "Non-binary",
  },
  {
    id: 40,
    first_name: "Colman",
    last_name: "Piel",
    email: "&quot;cpiel13@craigslist.org",
    gender: "Male",
  },
  {
    id: 41,
    first_name: "Curcio",
    last_name: "Whybray",
    email: "&quot;cwhybray14@newsvine.com",
    gender: "Male",
  },
  {
    id: 42,
    first_name: "Murielle",
    last_name: "Dreger",
    email: "&quot;mdreger15@sun.com",
    gender: "Female",
  },
  {
    id: 43,
    first_name: "Oralee",
    last_name: "Coslitt",
    email: "|&quot;ocoslitt16@ft.com",
    gender: "Female",
  },
  {
    id: 44,
    first_name: "Louise",
    last_name: "Dinkin",
    email: "&quot;ldinkin17@columbia.edu",
    gender: "Bigender",
  },
  {
    id: 45,
    first_name: "Dacy",
    last_name: "Tennewell",
    email: "&quot;dtennewell18@topsy.com",
    gender: "Female",
  },
  {
    id: 46,
    first_name: "Jamill",
    last_name: "Bubear",
    email: "&quot;jbubear19@drupal.org",
    gender: "Male",
  },
  {
    id: 47,
    first_name: "Pauletta",
    last_name: "Pydcock",
    email: "&quot;ppydcock1a@scribd.com",
    gender: "Female",
  },
  {
    id: 48,
    first_name: "Lalo",
    last_name: "Ashbe",
    email: "&quot;lashbe1b@businessinsider.com",
    gender: "Male",
  },
  {
    id: 49,
    first_name: "Adena",
    last_name: "Lembrick",
    email: "&quot;alembrick1c@economist.com",
    gender: "Female",
  },
  {
    id: 50,
    first_name: "Marline",
    last_name: "Mityushin",
    email: "|&quot;mmityushin1d@opensource.org",
    gender: "Female",
  },
  {
    id: 51,
    first_name: "Darius",
    last_name: "Padbury",
    email: "&quot;dpadbury1e@prnewswire.com",
    gender: "Male",
  },
  {
    id: 52,
    first_name: "Mitzi",
    last_name: "Pickavance",
    email: "&quot;mpickavance1f@people.com.cn",
    gender: "Female",
  },
  {
    id: 53,
    first_name: "Zilvia",
    last_name: "Northgraves",
    email: "&quot;znorthgraves1g@theguardian.com",
    gender: "Female",
  },
  {
    id: 54,
    first_name: "Niels",
    last_name: "De Gouy",
    email: "&quot;ndegouy1h@bbc.co.uk",
    gender: "Male",
  },
  {
    id: 55,
    first_name: "Freeman",
    last_name: "Dyet",
    email: "&quot;fdyet1i@php.net",
    gender: "Male",
  },
  {
    id: 56,
    first_name: "Mickie",
    last_name: "Bridgement",
    email: "&quot;mbridgement1j@alexa.com",
    gender: "Female",
  },
  {
    id: 57,
    first_name: "Ly",
    last_name: "Orhtmann",
    email: "&quot;lorhtmann1k@wikispaces.com",
    gender: "Male",
  },
  {
    id: 58,
    first_name: "Ellynn",
    last_name: "Causer",
    email: "&quot;ecauser1l@istockphoto.com",
    gender: "Female",
  },
  {
    id: 59,
    first_name: "Aron",
    last_name: "Ughetti",
    email: "&quot;aughetti1m@over-blog.com",
    gender: "Male",
  },
  {
    id: 60,
    first_name: "Effie",
    last_name: "Pannaman",
    email: "&quot;epannaman1n@craigslist.org",
    gender: "Female",
  },
  {
    id: 61,
    first_name: "Herschel",
    last_name: "Piechnik",
    email: "&quot;hpiechnik1o@soup.io",
    gender: "Agender",
  },
  {
    id: 62,
    first_name: "Chris",
    last_name: "Stoving",
    email: "&quot;cstoving1p@patch.com",
    gender: "Female",
  },
  {
    id: 63,
    first_name: "Marshal",
    last_name: "Hercules",
    email: "&quot;mhercules1q@mediafire.com",
    gender: "Male",
  },
  {
    id: 64,
    first_name: "Trev",
    last_name: "Sutherel",
    email: "&quot;tsutherel1r@whitehouse.gov",
    gender: "Male",
  },
  {
    id: 65,
    first_name: "Broderic",
    last_name: "Auckland",
    email: "&quot;bauckland1s@columbia.edu",
    gender: "Male",
  },
  {
    id: 66,
    first_name: "Jean",
    last_name: "McOwan",
    email: "&quot;jmcowan1t@4shared.com",
    gender: "Female",
  },
  {
    id: 67,
    first_name: "Jecho",
    last_name: "Bowkett",
    email: "&quot;jbowkett1u@cloudflare.com",
    gender: "Male",
  },
  {
    id: 68,
    first_name: "Walsh",
    last_name: "Paunton",
    email: "&quot;wpaunton1v@yellowpages.com",
    gender: "Male",
  },
  {
    id: 69,
    first_name: "Aimee",
    last_name: "Lorincz",
    email: "&quot;alorincz1w@miibeian.gov.cn",
    gender: "Female",
  },
  {
    id: 70,
    first_name: "Angelina",
    last_name: "Kemetz",
    email: "&quot;akemetz1x@dot.gov",
    gender: "Genderqueer",
  },
  {
    id: 71,
    first_name: "Sara",
    last_name: "Crickmore",
    email: "&quot;scrickmore1y@php.net",
    gender: "Female",
  },
  {
    id: 72,
    first_name: "Jeremie",
    last_name: "Liles",
    email: "&quot;jliles1z@squarespace.com",
    gender: "Genderfluid",
  },
  {
    id: 73,
    first_name: "Trace",
    last_name: "Alvarado",
    email: "&quot;talvarado20@elpais.com",
    gender: "Male",
  },
  {
    id: 74,
    first_name: "Veradis",
    last_name: "Wyld",
    email: "&quot;vwyld21@bbb.org",
    gender: "Female",
  },
  {
    id: 75,
    first_name: "Clywd",
    last_name: "Harhoff",
    email: "&quot;charhoff22@ifeng.com",
    gender: "Male",
  },
  {
    id: 76,
    first_name: "Mannie",
    last_name: "Georger",
    email: "&quot;mgeorger23@seesaa.net",
    gender: "Male",
  },
  {
    id: 77,
    first_name: "Wendell",
    last_name: "Illingsworth",
    email: "&quot;willingsworth24@webmd.com",
    gender: "Male",
  },
  {
    id: 78,
    first_name: "Margeaux",
    last_name: "Krug",
    email: "&quot;mkrug25@tumblr.com",
    gender: "Female",
  },
  {
    id: 79,
    first_name: "Brig",
    last_name: "Abbay",
    email: "&quot;babbay26@storify.com",
    gender: "Male",
  },
  {
    id: 80,
    first_name: "Fancy",
    last_name: "Golborn",
    email: "&quot;fgolborn27@independent.co.uk",
    gender: "Female",
  },
  {
    id: 81,
    first_name: "Nonah",
    last_name: "Boughtflower",
    email: "&quot;nboughtflower28@cocolog-nifty.com",
    gender: "Female",
  },
  {
    id: 82,
    first_name: "Blinni",
    last_name: "Denerley",
    email: "&quot;bdenerley29@slashdot.org",
    gender: "Female",
  },
  {
    id: 83,
    first_name: "Lovell",
    last_name: "Pittwood",
    email: "&quot;lpittwood2a@oaic.gov.au",
    gender: "Male",
  },
  {
    id: 84,
    first_name: "Delly",
    last_name: "Keson",
    email: "&quot;dkeson2b@rediff.com",
    gender: "Female",
  },
  {
    id: 85,
    first_name: "Brien",
    last_name: "Visco",
    email: "&quot;bvisco2c@pbs.org",
    gender: "Bigender",
  },
  {
    id: 86,
    first_name: "Colleen",
    last_name: "Radsdale",
    email: "&quot;cradsdale2d@desdev.cn",
    gender: "Female",
  },
  {
    id: 87,
    first_name: "Robena",
    last_name: "Blencowe",
    email: "&quot;rblencowe2e@java.com",
    gender: "Female",
  },
  {
    id: 88,
    first_name: "Gabriel",
    last_name: "Dadge",
    email: "&quot;gdadge2f@sfgate.com",
    gender: "Female",
  },
  {
    id: 89,
    first_name: "Huey",
    last_name: "Madgewick",
    email: "&quot;hmadgewick2g@craigslist.org",
    gender: "Male",
  },
  {
    id: 90,
    first_name: "Filippo",
    last_name: "Coldman",
    email: "&quot;fcoldman2h@google.ca",
    gender: "Male",
  },
  {
    id: 91,
    first_name: "Letty",
    last_name: "Desorts",
    email: "&quot;ldesorts2i@nydailynews.com",
    gender: "Female",
  },
  {
    id: 92,
    first_name: "Thurston",
    last_name: "Willimont",
    email: "&quot;twillimont2j@moonfruit.com",
    gender: "Male",
  },
  {
    id: 93,
    first_name: "Amity",
    last_name: "Artiss",
    email: "&quot;aartiss2k@phoca.cz",
    gender: "Female",
  },
  {
    id: 94,
    first_name: "Ermentrude",
    last_name: "Kornyakov",
    email: "&quot;ekornyakov2l@disqus.com",
    gender: "Female",
  },
  {
    id: 95,
    first_name: "Jenda",
    last_name: "Beathem",
    email: "&quot;jbeathem2m@prlog.org",
    gender: "Female",
  },
  {
    id: 96,
    first_name: "Odell",
    last_name: "Ivens",
    email: "&quot;oivens2n@mtv.com",
    gender: "Male",
  },
  {
    id: 97,
    first_name: "Janaye",
    last_name: "Morrish",
    email: "&quot;jmorrish2o@bbb.org",
    gender: "Female",
  },
  {
    id: 98,
    first_name: "Kiah",
    last_name: "Pinkney",
    email: "&quot;kpinkney2p@oaic.gov.au",
    gender: "Female",
  },
  {
    id: 99,
    first_name: "Calvin",
    last_name: "Stichall",
    email: "&quot;cstichall2q@craigslist.org",
    gender: "Male",
  },
  {
    id: 100,
    first_name: "Freemon",
    last_name: "Moggan",
    email: "&quot;fmoggan2r@unesco.org",
    gender: "Male",
  },
];

const usersCopy = structuredClone(users);
let tbody = document.querySelector("tbody");
let arrowUp = document.querySelector(".fa-arrow-up");
let searchInp = document.querySelector("#search");
let nameThElem = document.querySelector("name");
let idThElem = document.querySelector(".id");
let iDown = document.querySelector(".fa-solid fa-arrow-down");


searchInp.addEventListener("input", function (event) {
  let filtered = usersCopy.filter(
    (item) =>
      item.first_name
        .toLocaleLowerCase()
        .includes(event.target.value.toLocaleLowerCase()) ||
      item.last_name
        .toLocaleLowerCase()
        .includes(event.target.value.toLocaleLowerCase())
  );
  drowTable(filtered);
});

function drowTable(data) {
  tbody.innerHTML = "";
  data.forEach((elem) => {
    let trElem = document.createElement("tr");
    trElem.innerHTML += `
        <td>${elem.id}</td>
        <td>${elem.first_name} ${elem.last_name}</td>
        <td>${elem.email}</td>
        <td>${elem.gender}</td>
        `;
    tbody.append(trElem);
  });
}
drowTable(users);

idThElem.addEventListener("click", function () {
  
  let sorted = users.sort((a, b) => b.id - a.id);
  drowTable(sorted);
});


